### ISSUE TITLE
Tests to be added

### ISSUE THREAD

**Issue by victor-cortez** [ImpulsoGov/coronacidades-datasource#40]
## List of datasets tests checked

- [ ] br/cities/cases/full
- [ ] br/cities/cnes
- [ ] ~br/cities/embaixadores~
- [ ] br/cities/farolcovid/main
- [ ] br/cities/simulacovid/main
- [ ] br/cities/rt
- [ ] br/states/farolcovid/main
- [x] br/states/rt
- [ ] world/owid/heatmap
- [ ] inloco cities
- [ ] inloco states

## **Tests to be added**

Please use this issue to post tests you would like to see added to the datasource. Once the test is implemented in a PR the implementer can add the PR link as an answer to the test suggestion post.

 ### Format:
```markdown
**endpointname**

Data: [get_name].py
Tests:
- ...
Missing:
- ...
```

### Status of tests

Endpoint | Analysis | Good enough? | Who's doing it?
-- | -- | -- | -- | 
**br/cities/cases/full** | https://github.com/ImpulsoGov/coronacidades-datasource/issues/40#issuecomment-644290206 |  Not yet! | @francisconog  
**br/cities/cnes** | https://github.com/ImpulsoGov/coronacidades-datasource/issues/40#issuecomment-644291030 |  Not yet! | @francisconog 
**br/cities/simulacovid/main** | https://github.com/ImpulsoGov/coronacidades-datasource/issues/40#issuecomment-644291879 | Not yet! | @francisconog  
**br/cities/rt** | https://github.com/ImpulsoGov/coronacidades-datasource/issues/40#issuecomment-638998261 | Not yet! | @francisconog  
**br/cities/farolcovid/main** | https://github.com/ImpulsoGov/coronacidades-datasource/issues/40#issuecomment-644291340 | Not yet! | @francisconog
**br/states/rt** | https://github.com/ImpulsoGov/coronacidades-datasource/issues/40#issuecomment-639033264 | Not yet! | @fernandascovino 
**br/states/farolcovid/main** | https://github.com/ImpulsoGov/coronacidades-datasource/issues/40#issuecomment-644292487 | Not yet! | @fernandascovino 
**world/owid/heatmap** | https://github.com/ImpulsoGov/coronacidades-datasource/issues/40#issuecomment-644293416 | Not yet! | @fernandascovino 
**inloco (cities)** | https://github.com/ImpulsoGov/coronacidades-datasource/issues/40#issuecomment-644292384 | Not yet!  | @fernandascovino  
**inloco (states)** | https://github.com/ImpulsoGov/coronacidades-datasource/issues/40#issuecomment-644293282 | Not yet!  | @fernandascovino  

### Not used
---
**File**: get_embaixadores.py

Tests:
- Checks if the result is a pandas DataFrame
- Checks if there is no row with city_norm ending in space

**Comment by victor-cortez** [comment]
*Edit: Ran custom tests on our dataset is this is not currently true. Why?*

**br/cities/rt**

Script: get_cities_rt.py

Tests:
- Result must be a pandas DataFrame

Missing:
- Check if there are 3110 cities or more and if Rt most likely is between Rt low and Rt high (Rth >= Rtlikely >= Rtlow)

**Comment by victor-cortez** [comment]
**br/states/rt - DONE**

Script: get_states_rt.py

Tests:

- [x]  Result must be a pandas DataFrame

Missing:

- [x] There are exactly 27 states and if Rt most likely is between Rt low and Rt high (Rth >= Rtlikely >= Rtlow)

- [x] State that has rt must have at least 14 days of cases

**Comment by fernandascovino** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Organizar testes da API](https://trello.com/c/R9jAKLkl/403-organizar-testes-da-api)

**Comment by fernandascovino** [comment]
**br/cities/cases/full**

Script: get_cases.py

Tests:
- Result must be a pandas DataFrame
- No more than 5770 cities
- All cities must have non-null notification rate (when the city doesn't have one, it's from state)
- All cities must have non-null state notification rate

Missing:
- ...

**Comment by fernandascovino** [comment]
**br/cities/cnes**

Script: get_health.py

Tests:
- Result must be a pandas DataFrame

Missing: 
- In all cities the number of ventilators if smaller than the number of ICU beds.

**Comment by fernandascovino** [comment]
**br/cities/farolcovid/main**

Script: get_cities_farolcovid_main.py

Tests:
- Result must be a pandas DataFrame
- Checks if there are not more than 5770 cities
- Checks if all cities with subnotification have a rank (Note: only checks if counts are the same, maybe we can improve it to verify each row for a match)
- Checks if all cities have rt classification and growth (Note: same counting problem as before)
- Checks if the number of days for bed overload in the best scenario is smaller than in the worse scenario
- Checks if all the cities with overall alert null also have null classifications.

Missing:
- ...

**Comment by fernandascovino** [comment]
**br/cities/simulacovid/main**

Script: get_simulacovid_main.py

Tests:
- Result must be a pandas DataFrame
- There are exactly 5770 rows
- No roll must have null notification rate 

Missing:
- The number of days for bed overload in the best scenario must be smaller than in the worse scenario

**Comment by fernandascovino** [comment]
**Inloco (cities)**

Script: get_inloco_cities.py

Tests:
- Result must be a pandas DataFrame

Missing:
- No negative data

**Comment by fernandascovino** [comment]
**br/states/farolcovid/main**

Script: get_states_farolcovid_main.py

Tests:
- Result must be a pandas DataFrame
- There is at most 27 states
- All states with rt_classification must have rt_growth (Note: only checks if counts are the same, maybe we can improve it to verify each row for a match)
- The number of days for bed overload in the best scenario must be smaller than in the worse scenario
- All the states with overall alert null also must have null classifications.

Missing:
- ...

**Comment by fernandascovino** [comment]
**Inloco (states)**

Script: get_inloco_states.py

Tests:
- Result must be a pandas DataFrame

Missing:
- No negative data

**Comment by fernandascovino** [comment]
**world/owid/heatmap**

Script: get_owid_heatmap.py

Tests:
- Result must be a pandas DataFrame

Missing:
-  No negative data

**Comment by fernandascovino** [comment]
all updated!
